on:
  push:
    branches:
      - chore/remove-origami-token-ci-testing

jobs:
  create-new-version:
    runs-on: ubuntu-latest
    name: Create new version/tag
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0